"""
Generate the setup file that gives every country the
epbm_starting_maintenance timed modifier for the first two months.

Building maintenance modifiers from auto modifiers don't apply for a month or two
after the game has started. Alongside RGOs not producing anything for that time
many nations just declare bankruptcy day 1. This should prevent that from happening.

Run from inside tools/ (see tools/readme.txt):
    python3 epbm_generator/generate_starting_maintenance.py
"""

import re
import sys
from pathlib import Path

# Vanilla install candidates, first existing one wins. Add yours if needed.
VANILLA_GAME_CANDIDATES = [
    Path("/mnt/d/Program Files (x86)/Steam/steamapps/common/Europa Universalis V/game"),
    Path("/mnt/c/Program Files (x86)/Steam/steamapps/common/Europa Universalis V/game"),
    Path("/mnt/c/SteamLibrary/steamapps/common/Europa Universalis V/game"),
    Path("/mnt/d/SteamLibrary/steamapps/common/Europa Universalis V/game"),
    Path("D:/Program Files (x86)/Steam/steamapps/common/Europa Universalis V/game"),
    Path("C:/Program Files (x86)/Steam/steamapps/common/Europa Universalis V/game"),
    Path.home() / ".steam/steam/steamapps/common/Europa Universalis V/game",
]

MODIFIER = "epbm_starting_maintenance" # -100% building maintenance multiplier
START_DATE = "1337.4.1"
END_DATE = "1337.6.1"

_HERE = Path(__file__).resolve().parent
_MOD_ROOT = _HERE.parents[1]
OUTPUT = _MOD_ROOT / "main_menu" / "setup" / "start" / "99_epbm_starting_maintenance.txt"


def vanilla_countries_setup() -> Path:
    for game in VANILLA_GAME_CANDIDATES:
        p = game / "main_menu" / "setup" / "start" / "10_countries.txt"
        if p.exists():
            return p
    sys.exit("vanilla 10_countries.txt not found; add its install to VANILLA_GAME_CANDIDATES")


def start_tags(text: str) -> list[str]:
    """Tags defined at countries -> countries -> TAG, in file order, deduped."""
    text = re.sub(r"#[^\n]*", "", text)
    depth, stack, tags, seen = 0, [], [], set()
    for m in re.finditer(r"([A-Za-z0-9_]+)\s*=\s*\{|\{|\}", text):
        tok = m.group(0)
        if tok == "}":
            depth -= 1
            stack.pop()
        elif tok == "{":
            depth += 1
            stack.append("")
        else:
            depth += 1
            stack.append(m.group(1))
            if depth == 3 and stack[0] == "countries" and stack[1] == "countries":
                tag = m.group(1)
                if tag not in seen:
                    seen.add(tag)
                    tags.append(tag)
    if depth != 0:
        sys.exit(f"brace mismatch while parsing countries setup: depth {depth}")
    return tags


def main() -> None:
    src = vanilla_countries_setup()
    tags = start_tags(src.read_text(encoding="utf-8-sig"))
    entry = (
        "\t\t{tag} = {{\n"
        "\t\t\ttimed_modifier = {{\n"
        f'\t\t\t\tmodifier = "{MODIFIER}"\n'
        f"\t\t\t\tstart_date = {START_DATE}\n"
        f"\t\t\t\tdate = {END_DATE}\n"
        "\t\t\t\tsize = 1\n"
        "\t\t\t}}\n"
        "\t\t}}\n"
    )
    out = (
        "# GENERATED by tools/epbm_generator/generate_starting_maintenance.py. Do not edit.\n"
        f"# Every start-time country gets {MODIFIER} until {END_DATE}, applied\n"
        "# through setup so it exists before the AI's first decisions.\n"
        "countries = {\n\tcountries = {\n"
        + "".join(entry.format(tag=t) for t in tags)
        + "\t}\n}\n"
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_bytes(out.encode("utf-8"))
    print(f"{len(tags)} countries -> {OUTPUT.relative_to(_MOD_ROOT)}")


if __name__ == "__main__":
    main()
