# Configuration file for shared tool settings
# rename this file to config.ini after editing
[Paths]
log_directory = # Path to store log files ie: C:/users/username/Documents/ paradox interactive/ eu5 / logs
save_directory = # Path to Europa Universalis V save games ie: C:/users/username/Documents/Paradox Interactive/Europa Universalis V/save games
game_directory = # Path to Europa Universalis V

[Settings]
# How many months between autosaves should be kept ie (1 =1 autosave every month, 6 =  1 autosave every 6 months, 12 = 1 autosave every year)
autosave_month_interval = 6
