# Configuration file for shared tool settings
# rename this file to config.ini after editing
[Paths]
log_directory = # Path to store log files ie: C:/users/username/Documents/ paradox interactive/ eu5 / logs
save_directory = # Path to Europa Universalis V save games ie: C:/users/username/Documents/Paradox Interactive/Europa Universalis V/save games